version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: platform
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  flask_api:
    build:
      context: .
      dockerfile: Dockerfile.flask
    container_name: flask_api
    environment:
      - FLASK_APP=flask_api.py
      - FLASK_ENV=development
      - DATABASE_HOST=db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=my-secret-pw
      - DATABASE_NAME=platform
    depends_on:
      - db
    ports:
      - "5000:5000"

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: streamlit
    depends_on:
      - flask_api
    ports:
      - "8501:8501"
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=my-secret-pw
      - DATABASE_NAME=platform

volumes:
  db_data:
